# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
    ]
