# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20170406_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='EmergencyName',
            new_name='emergencyName',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='EmergencyRel',
            new_name='emergencyRel',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='EmergencyTlfNumber',
            new_name='emergencyTlfNumber',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
    ]
