# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20170410_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Room'),
        ),
    ]
