# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20170414_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount'),
        ),
    ]
