# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20170417_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dateOfRefund',
            field=models.DateField(null=True, verbose_name='Refunded Date'),
        ),
    ]
