# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_transaction_dateofrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinnerclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Amount')),
                ('menu', models.CharField(max_length=300, verbose_name='Menu')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Room')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='dinnerclub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Dinnerclub'),
        ),
    ]
