# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20170619_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dateOfRefund',
            field=models.DateField(blank=True, null=True, verbose_name='Refunded Date'),
        ),
    ]
