# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_auto_20171006_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='dateOfRefund',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='refunded',
        ),
        migrations.AddField(
            model_name='transaction',
            name='typeOfTransaction',
            field=models.CharField(choices=[('dept', 'Gæld'), ('expense', 'Udlæg')], default='dept', max_length=7, verbose_name='Type'),
        ),
    ]
