# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models


def setTransactionType(apps, schema_editor):
    tranModel = apps.get_model('cashier', 'transaction')
    trans = tranModel.objects.all()
    for tran in trans:
        if tran.amount < 0:
            tran.typeOfTransaction = 'dept'
            tran.amount * -1
        else:
            tran.typeOfTransaction = 'expense'
        tran.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_auto_20171006_1820'),
    ]

    operations = [
        migrations.RunPython(setTransactionType),
    ]
