# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models
# The amount of a transaction was modelled by a single number
# Since migration 0013 it has a 'type' fild, i forgot to save the value
# in migration 0013. which changed the negative numbers. The migrations
#fixes this problem By multiplying every transaction of type dept with -1



def fixTransactionAmount(apps, schema_editor):
    tranModel = apps.get_model('cashier', 'transaction')
    trans = tranModel.objects.all()
    for tran in trans:
        if tran.typeOfTransaction == 'dept':
            tran.amount *= -1
            tran.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0013_update_transaction'),
    ]

    operations = [
        migrations.RunPython(fixTransactionAmount),
    ]
