# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_fix_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='typeOfTransaction',
            field=models.CharField(choices=[('debt', 'Gæld'), ('expense', 'Udlæg')], default='debt', max_length=7, verbose_name='Type'),
        ),
    ]
