# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0015_auto_20171108_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashier.Transaction')),
                ('refunded', models.BooleanField(default=False, verbose_name='Moved to Chashier account')),
                ('dateOfRefund', models.DateField(blank=True, null=True, verbose_name='Date of transfer')),
            ],
            bases=('cashier.transaction',),
        ),
    ]
