# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0017_auto_20171108_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dateOfRefund',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of transfer'),
        ),
    ]
