# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models

# I forgot to change the value of dinner clubs...
# Extra i forgot to save the value

def fixDinnerClub(apps, schema_editor):
    tranModel = apps.get_model('cashier', 'transaction')
    trans = tranModel.objects.all()
    for tran in trans:
        if tran.amount < 0:
            tran.amount *= -1
            tran.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0020_fix_dinnerClub'),
    ]

    operations = [
        migrations.RunPython(fixDinnerClub),
    ]
