# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0021_fix_dinnerClub'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Arkiveret'),
        ),
    ]
