# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-06 05:35
from __future__ import unicode_literals

import cashier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('nickName', models.CharField(blank=True, max_length=200, verbose_name='Nickname')),
                ('tlfNumber', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('EmergencyName', models.CharField(blank=True, max_length=200, verbose_name='Emergency Name')),
                ('EmergencyRel', models.CharField(blank=True, max_length=200, verbose_name='Emergency relationship type')),
                ('EmergencyTlfNumber', models.IntegerField(blank=True, null=True, verbose_name='Emergency phone')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('room', models.ForeignKey(on_delete=cashier.models.Room, to='cashier.Room')),
            ],
        ),
    ]
