# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('nickName', models.CharField(default='', max_length=200, verbose_name='Nickname')),
                ('tlfNumber', models.IntegerField(verbose_name='Phone Number')),
                ('mail', models.EmailField(max_length=254)),
                ('EmergencyName', models.CharField(max_length=200, verbose_name='Emergency Name')),
                ('EmergencyRel', models.CharField(max_length=200, verbose_name='Emergency relationship type')),
                ('EmergencyTlfNumber', models.IntegerField(verbose_name='Emergency phone')),
            ],
        ),
    ]
